<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $title }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #ccc; padding: 6px; text-align: center; font-size: 12px; }
        th { background-color: #f3f4f6; }
        .text-left { text-align: left; }
        .text-right { text-align: right; }
        .text-sm { font-size: 12px; }
        .font-bold { font-weight: bold; }
        .mb-4 { margin-bottom: 1rem; }
        .mt-2 { margin-top: 0.5rem; }
        .uppercase { text-transform: uppercase; }
    </style>
</head>
<body>

    <h2 class="text-center font-bold uppercase mb-4">{{ $title }}</h2>

    {{-- School and Section Info --}}
    <div class="mb-4">
        <p class="text-sm"><strong>School:</strong> {{ $school_info['name'] ?? 'N/A' }}</p>
        <p class="text-sm"><strong>Academic Year:</strong> {{ $academic_year['name'] }}</p>
        <p class="text-sm"><strong>Quarter:</strong> {{ $quarter['name'] }} ({{ $quarter['start_date'] }} - {{ $quarter['end_date'] }})</p>
        <p class="text-sm"><strong>Section:</strong> {{ $section['name'] }} | {{ $section['year_level'] }}</p>
        <p class="text-sm"><strong>Advisor:</strong> {{ $advisor['name'] }} ({{ $advisor['email'] }})</p>
    </div>

    {{-- Attendance Table --}}
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th class="text-left">Student Name</th>
                <th>Student ID</th>
                <th>LRN</th>
                <th>Total Days</th>
                <th>Present</th>
                <th>Absent</th>
                <th>Late</th>
                <th>Excused</th>
                <th>Attendance %</th>
                <th>Tardiness %</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($summaries as $index => $summary)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td class="text-left">{{ $summary['student']['full_name'] }}</td>
                    <td>{{ $summary['student']['student_id'] }}</td>
                    <td>{{ $summary['student']['lrn'] }}</td>
                    <td>{{ $summary['attendance_data']['total_school_days'] }}</td>
                    <td>{{ $summary['attendance_data']['present_days'] }}</td>
                    <td>{{ $summary['attendance_data']['absent_days'] }}</td>
                    <td>{{ $summary['attendance_data']['late_days'] }}</td>
                    <td>{{ $summary['attendance_data']['excused_days'] }}</td>
                    <td>{{ $summary['attendance_data']['attendance_percentage'] }}%</td>
                    <td>{{ $summary['attendance_data']['tardiness_percentage'] }}%</td>
                    <td>{{ $summary['attendance_data']['attendance_status'] }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    {{-- Class Statistics --}}
    <div class="mt-2 mb-4">
        <h4 class="font-bold mt-2">Class Statistics:</h4>
        @foreach ($class_statistics as $key => $value)
            <p class="text-sm">{{ ucfirst(str_replace('_', ' ', $key)) }}: <strong>{{ is_numeric($value) ? number_format($value, 2) : $value }}</strong></p>
        @endforeach
    </div>

    <div class="text-right text-sm mt-2">
        <p>Generated by: {{ $generated_by }}</p>
        <p>Generated at: {{ $generated_at }}</p>
    </div>

</body>
</html>
